POST http://localhost:8080/bot/message
Content-Type: application/json

{
	  "event":"continue",
    "message":{
      "code":"message",
      "type":"text",
      "body":"Antonio Smith"
    },
    "settings":{
      "engine":{
        "type":"WitAi",
        "settings":{
          "token":"VALID_TOKEN"
        }
      }
    },
    "data":{},
    "context":{"contexts":["ask_for_name"]}
}

###
POST http://localhost:8080/bot/message
Content-Type: application/json

{
	  "event":"continue",
    "message":{
      "code":"message",
      "type":"text",
      "body":"Technical"
    },
    "settings":{
      "engine":{
        "type":"WitAi",
        "settings":{
          "token":"VALID_TOKEN"
        }
      }
    },
    "data":{},
    "context":{"contexts":["ask_for_support_type"]}
}
